name: Build and Push Terraform CI Container Image

on:
    push:
        branches: [main]

jobs:
  build-push-image:
    runs-on: ubuntu-latest

    permissions:
        contents: write
        packages: write

    env:
      REPOSITORY: ghcr.io/UKHSA-Internal/devops-terraform-ci

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Bump Version and Push Tag
      #   id: tag_version
      #   uses: mathieudutour/github-tag-action@v6.2
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.REPOSITORY }}:latest
          # ${{ env.REPOSITORY }}:${{ steps.tag_version.outputs.new_tag }}
